### ISSUE TITLE
Bug: When doing transfer learning model throws shapes and refuses to test

### ISSUE THREAD

**Issue by ftyers** [coqui-ai/STT#1829]
```
root@2335bec676a7:/code# bash -x train.sh ; bash -x test.sh ; bash -x lm.sh ; bash -x export.sh 
+ LLENGUA=el
+ mkdir -p checkpoints
+ TF_CUDNN_RESET_RND_GEN_STATE=1
+ python3 train.py --show_progressbar True --train_cudnn --epochs 25 --es_epochs 3 --max_to_keep 3 --drop_source_layers 2 --train_batch_size 8 --test_batch_size 8 --dev_batch_size 8 --alphabet_config_path /media/cv-corpus-6.1-2020-12-11/el/alphabet.txt --save_checkpoint_dir checkpoints --load_checkpoint_dir deepspeech-0.9.3-checkpoint/ --train_files /media/cv-corpus-6.1-2020-12-11/el/clips/train.csv --dev_files /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv --test_files /media/cv-corpus-6.1-2020-12-11/el/clips/test.csv
W WARNING: You specified different values for --load_checkpoint_dir and --save_checkpoint_dir, but you are running training and testing in a single invocation. The testing step will respect --load_checkpoint_dir, and thus WILL NOT TEST THE CHECKPOINT CREATED BY THE TRAINING STEP. Train and test in two separate invocations, specifying the correct --load_checkpoint_dir in both cases, or use the same location for loading and saving.
I Loading best validating checkpoint from deepspeech-0.9.3-checkpoint/best_dev-1466475
I Loading variable from checkpoint: beta1_power
I Loading variable from checkpoint: beta2_power
I Loading variable from checkpoint: cudnn_lstm/opaque_kernel
I Loading variable from checkpoint: cudnn_lstm/opaque_kernel/Adam
I Loading variable from checkpoint: cudnn_lstm/opaque_kernel/Adam_1
I Loading variable from checkpoint: global_step
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/bias/Adam
I Loading variable from checkpoint: layer_1/bias/Adam_1
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_1/weights/Adam
I Loading variable from checkpoint: layer_1/weights/Adam_1
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/bias/Adam
I Loading variable from checkpoint: layer_2/bias/Adam_1
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_2/weights/Adam
I Loading variable from checkpoint: layer_2/weights/Adam_1
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/bias/Adam
I Loading variable from checkpoint: layer_3/bias/Adam_1
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_3/weights/Adam
I Loading variable from checkpoint: layer_3/weights/Adam_1
I Loading variable from checkpoint: learning_rate
I Initializing variable: layer_5/bias
I Initializing variable: layer_5/bias/Adam
I Initializing variable: layer_5/bias/Adam_1
I Initializing variable: layer_5/weights
I Initializing variable: layer_5/weights/Adam
I Initializing variable: layer_5/weights/Adam_1
I Initializing variable: layer_6/bias
I Initializing variable: layer_6/bias/Adam
I Initializing variable: layer_6/bias/Adam_1
I Initializing variable: layer_6/weights
I Initializing variable: layer_6/weights/Adam
I Initializing variable: layer_6/weights/Adam_1
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:01:58 | Steps: 289 | Loss: 150.440151                                                                                 
Epoch 0 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 118.190063 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 118.190063 to: checkpoints/best_dev-1466764
--------------------------------------------------------------------------------
Epoch 1 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 112.087529                                                                                 
Epoch 1 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 108.616011 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 108.616011 to: checkpoints/best_dev-1467053
--------------------------------------------------------------------------------
Epoch 2 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 99.295714                                                                                  
Epoch 2 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 94.945360 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 94.945360 to: checkpoints/best_dev-1467342
--------------------------------------------------------------------------------
Epoch 3 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 83.251152                                                                                  
Epoch 3 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 80.855902 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 80.855902 to: checkpoints/best_dev-1467631
--------------------------------------------------------------------------------
Epoch 4 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 69.715410                                                                                  
Epoch 4 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 71.249459 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 71.249459 to: checkpoints/best_dev-1467920
--------------------------------------------------------------------------------
Epoch 5 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 60.592198                                                                                  
Epoch 5 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 65.730284 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 65.730284 to: checkpoints/best_dev-1468209
--------------------------------------------------------------------------------
Epoch 6 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 54.503149                                                                                  
Epoch 6 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 62.088597 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 62.088597 to: checkpoints/best_dev-1468498
--------------------------------------------------------------------------------
Epoch 7 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 50.214056                                                                                  
Epoch 7 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 59.742852 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 59.742852 to: checkpoints/best_dev-1468787
--------------------------------------------------------------------------------
Epoch 8 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 46.843261                                                                                  
Epoch 8 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 58.021387 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 58.021387 to: checkpoints/best_dev-1469076
--------------------------------------------------------------------------------
Epoch 9 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 44.179930                                                                                  
Epoch 9 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 56.870370 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                      
I Saved new best validating model with loss 56.870370 to: checkpoints/best_dev-1469365
--------------------------------------------------------------------------------
Epoch 10 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 41.892102                                                                                 
Epoch 10 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 55.820707 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 55.820707 to: checkpoints/best_dev-1469654
--------------------------------------------------------------------------------
Epoch 11 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 39.862837                                                                                 
Epoch 11 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 54.944336 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 54.944336 to: checkpoints/best_dev-1469943
--------------------------------------------------------------------------------
Epoch 12 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 38.057278                                                                                 
Epoch 12 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 54.388507 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 54.388507 to: checkpoints/best_dev-1470232
--------------------------------------------------------------------------------
Epoch 13 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 36.473011                                                                                 
Epoch 13 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 53.870240 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 53.870240 to: checkpoints/best_dev-1470521
--------------------------------------------------------------------------------
Epoch 14 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 34.977883                                                                                 
Epoch 14 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 53.513870 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 53.513870 to: checkpoints/best_dev-1470810
--------------------------------------------------------------------------------
Epoch 15 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 33.688198                                                                                 
Epoch 15 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 53.115888 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 53.115888 to: checkpoints/best_dev-1471099
--------------------------------------------------------------------------------
Epoch 16 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 32.372648                                                                                 
Epoch 16 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.871868 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 52.871868 to: checkpoints/best_dev-1471388
--------------------------------------------------------------------------------
Epoch 17 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 31.218126                                                                                 
Epoch 17 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.653315 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 52.653315 to: checkpoints/best_dev-1471677
--------------------------------------------------------------------------------
Epoch 18 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 30.027386                                                                                 
Epoch 18 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.504788 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 52.504788 to: checkpoints/best_dev-1471966
--------------------------------------------------------------------------------
Epoch 19 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 28.985256                                                                                 
Epoch 19 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.341194 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 52.341194 to: checkpoints/best_dev-1472255
--------------------------------------------------------------------------------
Epoch 20 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 28.030723                                                                                 
Epoch 20 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.125567 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 52.125567 to: checkpoints/best_dev-1472544
--------------------------------------------------------------------------------
Epoch 21 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 27.094344                                                                                 
Epoch 21 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.197986 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
--------------------------------------------------------------------------------
Epoch 22 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 26.126977                                                                                 
Epoch 22 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.169392 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
--------------------------------------------------------------------------------
Epoch 23 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 25.329971                                                                                 
Epoch 23 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 51.964646 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
I Saved new best validating model with loss 51.964646 to: checkpoints/best_dev-1473411
--------------------------------------------------------------------------------
Epoch 24 |   Training | Elapsed Time: 0:01:55 | Steps: 289 | Loss: 24.420492                                                                                 
Epoch 24 | Validation | Elapsed Time: 0:00:27 | Steps: 176 | Loss: 52.078386 | Dataset: /media/cv-corpus-6.1-2020-12-11/el/clips/dev.csv                     
--------------------------------------------------------------------------------
I FINISHED optimization in 1:00:13.756332
I Loading best validating checkpoint from deepspeech-0.9.3-checkpoint/best_dev-1466475
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
I Loading variable from checkpoint: global_step
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_5/bias
I Loading variable from checkpoint: layer_5/weights
I Loading variable from checkpoint: layer_6/bias
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    ds_train.run_script()
  File "/code/training/coqui_stt_training/train.py", line 986, in run_script
    absl.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/code/training/coqui_stt_training/train.py", line 962, in main
    test()
  File "/code/training/coqui_stt_training/train.py", line 682, in test
    samples = evaluate(FLAGS.test_files.split(','), create_model)
  File "/code/training/coqui_stt_training/evaluate.py", line 87, in evaluate
    load_graph_for_evaluation(session)
  File "/code/training/coqui_stt_training/util/checkpoints.py", line 151, in load_graph_for_evaluation
    _load_or_init_impl(session, methods, allow_drop_layers=False)
  File "/code/training/coqui_stt_training/util/checkpoints.py", line 98, in _load_or_init_impl
    return _load_checkpoint(session, ckpt_path, allow_drop_layers, allow_lr_init=allow_lr_init)
  File "/code/training/coqui_stt_training/util/checkpoints.py", line 71, in _load_checkpoint
    v.load(ckpt.get_tensor(v.op.name), session=session)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/variables.py", line 1033, in load
    session.run(self.initializer, {self.initializer.inputs[1]: value})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (29,) for Tensor 'layer_6/bias/Initializer/zeros:0', which has shape '(37,)'
```

**Comment by ftyers** [comment]
Note that if the shapes **do** match (accidentally) like English and Basque, then the training proceeds and you get bad output:

![imatge](https://user-images.githubusercontent.com/449545/113914601-a19a3c00-97d5-11eb-8696-2a57fa35bab4.png)

**Comment by reuben** [comment]
> W WARNING: You specified different values for --load_checkpoint_dir and --save_checkpoint_dir, but you are running training and testing in a single invocation. The testing step will respect --load_checkpoint_dir, and thus WILL NOT TEST THE CHECKPOINT CREATED BY THE TRAINING STEP. Train and test in two separate invocations, specifying the correct --load_checkpoint_dir in both cases, or use the same location for loading and saving.

It's right there in the log ;)

**Comment by reuben** [comment]
Maybe it should be an error instead? I intend to refactor the training code so that `train.py` isn't so overloaded with functionality which would fix this, but that's gonna take a while. Feel free to leave the bug open I guess if some easier solution pops up in the mean time.

**Comment by ftyers** [comment]
I think a reasonable approach would be to just throw the user back to the shell saying "run evaluate.py with these arguments to test". In addition evaluate.py runs a lot faster.
