### ISSUE TITLE
Bug: ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /path/to/.local/lib/python3.7/site-packages/stt/lib/libstt.so)

### ISSUE THREAD

**Issue by isammitr** [coqui-ai/STT#1907]
**Description of the bug and steps to Reproduce the behaviour**
I was trying to follow the "Quickstart:Deployment" section. When I ran the final command `stt --model ...` It did not give any output but directly the following Traceback:

```
Traceback (most recent call last):
  File "/home/sammit/.local/bin/stt", line 5, in <module>
    from stt.client import main
  File "/home/sammit/.local/lib/python3.7/site-packages/stt/__init__.py", line 23, in <module>
    from stt.impl import Version as version
  File "/home/sammit/.local/lib/python3.7/site-packages/stt/impl.py", line 13, in <module>
    from . import _impl
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/sammit/.local/lib/python3.7/site-packages/stt/lib/libstt.so)
```

The [documentation](https://stt.readthedocs.io/en/latest/SUPPORTED_PLATFORMS.html?highlight=glibc#linux-amd64-with-gpu) says Coqui STT supports GLIBC>=2.19 and I have GLIBC=2.23. Please see below the output when I run `ldd --version`

```
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

And my OS Description:
```  
Operating System: Ubuntu 16.04.6 LTS
            Kernel: Linux 4.4.0-184-generic
      Architecture: x86-64
```

**Comment by reuben** [comment]
This is happening because your operating system is too old. You'll have to build the Python package from source (or upgrade your OS).

-- reuben

**Comment by zubairahmed-ai** [comment]
Just faced this. I am Ubuntu 18.04, what should I do? @reuben

**Comment by zubairahmed-ai** [comment]
```
 stt --model stt-0.9.3-models.pbmm --scorer stt-0.9.3-models.scorer --audio speech26-510k.wav
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/stt/bin/stt", line 5, in <module>
    from stt.client import main
  File "/home/ubuntu/anaconda3/envs/stt/lib/python3.6/site-packages/stt/__init__.py", line 23, in <module>
    from stt.impl import Version as version
  File "/home/ubuntu/anaconda3/envs/stt/lib/python3.6/site-packages/stt/impl.py", line 13, in <module>
    from . import _impl
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/ubuntu/anaconda3/envs/stt/lib/python3.6/site-packages/stt/lib/libstt.so)

```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

```

**Comment by reuben** [comment]
Latest packages now are built on manylinux_2_24 and need glibc 2.24 or newer.

**Comment by zubairahmed-ai** [comment]
Great, I have now upgraded but good to know this too
