### ISSUE TITLE
Bug: /code/kenlm/build/bin/lmplz: error while loading shared libraries: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DerekChia** [coqui-ai/STT#1944]
**Describe the bug**
I got the following error when running the command as instructed in [Train the Language Model](https://stt.readthedocs.io/en/latest/LANGUAGE_MODEL.html#train-the-language-model)
```
/code/kenlm/build/bin/lmplz: error while loading shared libraries: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Run the command `python3 data/lm/generate_lm.py \
  --input_txt /experiment/librispeech-lm-norm.txt.gz \
  --output_dir . \
  --top_k 500000 \
  --kenlm_bins /code/kenlm/build/bin/ \
  --arpa_order 5 \
  --max_arpa_memory "85%" \
  --arpa_prune "0|0|1" \
  --binary_a_bits 255 \
  --binary_q_bits 8 \
  --binary_type trie` 
2. See full error below

```
================
== TensorFlow ==
================

NVIDIA Release 20.06-tf1 (build 13409399)
TensorFlow Version 1.15.2

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
Copyright 2017-2020 The TensorFlow Authors.  All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

python3 data/lm/generate_lm.py \
  --input_txt /experiment/librispeech-lm-norm.txt.gz \
  --output_dir . \
  --top_k 500000 \
  --kenlm_bins /code/kenlm/build/bin/ \
  --arpa_order 5 \
  --max_arpa_memory "85%" \
  --arpa_prune "0|0|1" \
  --binary_a_bits 255 \
  --binary_q_bits 8 \
  --binary_type trieroot@f48fa96f3b9c:/code# python3 data/lm/generate_lm.py \
>   --input_txt /experiment/librispeech-lm-norm.txt.gz \
>   --output_dir . \
>   --top_k 500000 \
>   --kenlm_bins /code/kenlm/build/bin/ \
>   --arpa_order 5 \
>   --max_arpa_memory "85%" \
>   --arpa_prune "0|0|1" \
>   --binary_a_bits 255 \
>   --binary_q_bits 8 \
>   --binary_type trie

Converting to lowercase and counting word occurrences ...
| |                                               #                                                                   | 40418260 Elapsed Time: 0:13:52

Saving top 500000 words ...

Calculating word statistics ...
  Your text file has 803288729 words in total
  It has 973673 unique words
  Your top-500000 words are 99.9354 percent of all words
  Your most common word "the" occurred 49059384 times
  The least common word in your top-k is "corders" with 2 times
  The first word with 3 occurrences is "zungwan" at place 420186

Creating ARPA file ...
/code/kenlm/build/bin/lmplz: error while loading shared libraries: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "data/lm/generate_lm.py", line 210, in <module>
    main()
  File "data/lm/generate_lm.py", line 201, in main
    build_lm(args, data_lower, vocab_str)
  File "data/lm/generate_lm.py", line 97, in build_lm
    subprocess.check_call(subargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/code/kenlm/build/bin/lmplz', '--order', '5', '--temp_prefix', '.', '--memory', '85%', '--text', './lower.txt.gz', '--arpa', './lm.arpa', '--prune', '0', '0', '1']' returned non-zero exit status 127.
root@f48fa96f3b9c:/code# 

```

**Expected behavior**
I should be able to generate `lm.binary` and `vocab-500000.txt`

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Using docker ghcr.io/coqui-ai/stt-train:latest
- **TensorFlow version (use command below)**: 1.15.2
- **Python version**: 3.6.9
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**: 11.2
- **GPU model and memory**: Quadro P4200
- **Exact command to reproduce**:

**Solution**

I actually got it working by removing the original KenLM and re-compiling KenLM using the following command in the `/code` folder

```
git clone https://github.com/kpu/kenlm.git && cd kenlm && mkdir build && cd build/ && cmake .. && make -j 4
```

**Comment by reuben** [comment]
Can't reproduce on latest image, feel free to reopen if you're seeing this in a specific context.
