### ISSUE TITLE
Bug: LinguaLibre stops downloading at 51%

### ISSUE THREAD

**Issue by wasertech** [coqui-ai/STT#2047]
# Can't download LiguaLibre using import script

## Problem

When you try to download LinguaLibre (at least for the french part), down stream stops every time at 51%.

## How to reproduce

Just run the following command:

```
+ python /home/trainer/stt/bin/import_lingua_libre.py --qId 21 --iso639-3 fra --english-name French --validate_label_locale /home/trainer/fr/validate_label.py --bogus-records /home/trainer/fr/lingua_libre_skiplist.txt /mnt/extracted/data/lingualibre
No path "/mnt/extracted/data/lingualibre" - creating ...
No archive "/mnt/extracted/data/lingualibre/Q21-fra-French.zip" - downloading...
 51%|█████████████████████████████████████████████████████████▍                                                      | 1083305868/2112950650 [02:55<02:46, 6168695.24it/s]
No directory "/mnt/extracted/data/lingualibre/lingua_libre" - extracting archive...
Traceback (most recent call last):
  File "/home/trainer/stt/bin/import_lingua_libre.py", line 266, in <module>
    _download_and_preprocess_data(target_dir=CLI_ARGS.target_dir)
  File "/home/trainer/stt/bin/import_lingua_libre.py", line 41, in _download_and_preprocess_data
    _maybe_extract(target_dir, ARCHIVE_DIR_NAME, archive_path)
  File "/home/trainer/stt/bin/import_lingua_libre.py", line 53, in _maybe_extract
    with zipfile.ZipFile(archive_path) as zip_f:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

## Expected behavior
The compressed data should be entirely downloaded.

## Hot fix

You can manually download the data using `wget --continue https://lingualibre.org/datasets/Q21-fra-French.zip`.

After chatting with @lissyx we concluded that this fix needs more than adding the `--continue` flag to wget as Coqui STT uses [`util/downloader.py`](https://github.com/coqui-ai/STT/blob/main/training/coqui_stt_training/util/downloader.py) to download data.

**Comment by lissyx** [comment]
Just to be clear, this repros with pure `wget` here, so it is likely a server-side issue. Nevertheless, I think making the downloader code more reliable to failures is a nice goal.

**Comment by wasertech** [comment]
Exactly we need a more robust downloader  for multi-chunk archives and poor connection areas.

**Comment by wasertech** [comment]
You can add `bin/import_m-ailabs.py`.

```
root@95a2d562414f:/code/data/lm# python /code/bin/import_m-ailabs.py --skiplist monsieur_lecoq,les_mysteres_de_paris --language fr_FR /mnt/extracted/data/M-AILABS/2021-12-20 17:38:53.774066: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
WARNING: No --validate_label_locale specified, you might end with inconsistent dataset.
No path "/mnt/extracted/data/M-AILABS" - creating ...
No archive "/mnt/extracted/data/M-AILABS/fr_FR.tgz" - downloading...
8343it [00:00, 16904868.73it/s]
No directory "/mnt/extracted/data/M-AILABS/fr_FR" - extracting archive...
Traceback (most recent call last):
  File "/code/bin/import_m-ailabs.py", line 242, in <module>
    _download_and_preprocess_data(target_dir=CLI_ARGS.target_dir)
  File "/code/bin/import_m-ailabs.py", line 37, in _download_and_preprocess_data
    _maybe_extract(target_dir, ARCHIVE_DIR_NAME, archive_path)
  File "/code/bin/import_m-ailabs.py", line 49, in _maybe_extract
    tar = tarfile.open(archive_path)
  File "/usr/lib/python3.6/tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by wasertech** [comment]
`import_slr94.py` (prev. `import_mls_english.py`) is also affected as the dataset is served from AWS. [See](https://github.com/coqui-ai/STT/pull/2070)

**Comment by reuben** [comment]
@wasertech is this still valid with your recent PRs?

**Comment by wasertech** [comment]
@reuben unless we change something in the downloader, then it’s still an issue yes.

**Comment by wasertech** [comment]
Thinking about this issue, maybe using `allow_redirects=True` for `requests.get` in [util/downloader.py](https://github.com/coqui-ai/STT/blob/597e6ebb5c1a398c10b3a84810f93c1ce96d7926/training/coqui_stt_training/util/downloader.py#L28) might solve our downloading problems.

```python
req = requests.get(archive_url, stream=True, allow_redirects=True) #:28
```

I'll have to make some tests.
