### ISSUE TITLE
Bug: CCPMF: Fix BadZipFile

### ISSUE THREAD

**Issue by wasertech** [coqui-ai/STT#2066]
# Fix `STT.bin.import_ccpmf.zipfile.BadZipFile`

## Problem
If you'd like to import CCPMF, `import_ccpmf.py` fails to extract the multi-part archives because it uses an old version of the `zipfile` python module.

## How to reproduce
```
root@9ef0d1da59d6:/code# python bin/import_ccpmf.py /mnt/extracted/data/ccpmf/
2022-01-06 17:03:09.749901: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
WARNING: No --validate_label_locale specified, you might end with inconsistent dataset.
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.001 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.001: OK 863d39a06a388c6491c6ff2f6450b151f38f1b57
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.002 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.002: OK 2f3a0305aa04c61220bb00b5a4e553e45dbf12e1
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.003 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.003: OK 5e55e9f1f844097349188ac875947e5a3d7fe9f1
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.004 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.004: OK 8bf54842cf07948ca5915e27a8bd5fa5139c06ae
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.005 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.005: OK c8963504aadc015ac48f9af80058a0bb3440b94f
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.006 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.006: OK d95e225e908621d83ce4e9795fd108d9d310e244
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.007 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.007: OK de6ed9c2b0ee80ca879aae8ba7923cc93217d811
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.008 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.008: OK 234283c47dacfcd4450d836c52c25f3e807fc5f2
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.009 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.009: OK 4e6b67a688639bb72f8cd81782eaba604a8d32a6
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.010 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.010: OK 4165a51389777c8af8e6253d87bdacb877e8b3b0
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.011 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.011: OK 34322e7009780d97ef5bd02bf2f2c7a31f00baff
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.012 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.012: OK 48c5be3b2ca9d6108d525da6a03e91d93a95dbac
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.013 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.013: OK 87573172f506a189c2ebc633856fe11a2e9cd213
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.014 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.014: OK 6ab2c9e508e9278d5129f023e018725c4a7c69e8
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.015 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.015: OK 4f84df831ef46dce5d3ab3e21817687a2d8c12d0
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.016 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.016: OK e69bfb079885c299cb81080ef88b1b8b57158aa6
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.017 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.017: OK 5f764ba788ee273981cf211b242c29b49ca22c5e
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.018 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.018: OK b6aa81a959525363223494830c1e7307d4c4bae6
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.019 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.019: OK 91ddcf43c7bf113a6f2528b857c7ec22a50a148a
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.020 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.020: OK fa1b29273dd77b9a7494983a2f9ae52654b931d7
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.021 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.021: OK 1113aef4f5e2be2f7fbf2d54b6c710c1c0e7135f
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.022 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.022: OK ce6420d5d0b6b5135ba559f83e1a82d4d615c470
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.023 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.023: OK d0976ed292ac24fcf1590d1ea195077c74b05471
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.024 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.024: OK ec746cd6af066f62d9bf8d3b2f89174783ff4e3c
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.025 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.025: OK 570d9e1e84178e32fd867171d4b3aaecda1fd4fb
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.026 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.026: OK c29ccc7467a75b2cae3d7f2e9fbbb2ab276cb8ac
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.027 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.027: OK 08406a51146d88e208704ce058c060a1e44efa50
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.028 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.028: OK 199aedad733a78ea1e7d47def9c71c6fd5795e02
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.029 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.029: OK db856a068f92fb4f01f410bba42c7271de0f231a
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.030 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.030: OK e3c0135f16c6c9d25a09dcb4f99a685438a84740
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.031 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.031: OK e51b8bb9c0ae4339f98b4f21e6d29b825109f0ac
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.032 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.032: OK be5e80cbc49b59b31ae33c30576ef0e1a162d84e
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.033 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.033: OK 501df58e3ff55fcfd75b93dab57566dc536948b8
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.034 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.034: OK 1a114875811a8cdcb8d85a9f6dbee78be3e05131
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.035 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.035: OK 465d824e7ee46448369182c0c28646d155a2249b
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.036 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.036: OK 37f341b1b266d143eb73138c31cfff3201b9d619
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.037 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.037: OK 9e7d8255987a8a77a90e0d4b55c8fd38b9fb5694
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.038 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.038: OK 54886755630cb080a53098cb1b6c951c6714a143
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.039 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.039: OK 4b7cbb0154697be795034f7a49712e882a97197a
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.040 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.040: OK c8e1e565a0e7a1f6ff1dbfcefe677aa74a41d2f2
No directory "/mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020" - extracting archive /mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip ...
Traceback (most recent call last):
  File "bin/import_ccpmf.py", line 727, in <module>
    csv_url=DATASET_RELEASE_CSV, target_dir=PARAMS.target_dir
  File "bin/import_ccpmf.py", line 262, in _download_and_preprocess_data
    "transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020.zip",
  File "bin/import_ccpmf.py", line 294, in _maybe_extract
    with zipfile.ZipFile(final_archive) as zip_f:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1194, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python3.6/zipfile.py", line 287, in _EndRecData
    return _EndRecData64(fpin, -sizeEndCentDir, endrec)
  File "/usr/lib/python3.6/zipfile.py", line 233, in _EndRecData64
    raise BadZipFile("zipfiles that span multiple disks are not supported")
zipfile.BadZipFile: zipfiles that span multiple disks are not supported
```

### Expected behavior
> A clear and concise description of what you expected to happen.

I expect the archives to be extracted and the data imported.

### Solution

As [StackOverflow](https://stackoverflow.com/questions/17664262/python-zipfile-module-erroneously-thinks-i-have-a-zipfile-that-spans-multiple-di) discoverd, a quick fix for python 3.6 is to use `zipfile38` instead.

```python3
#import zipfile
import zipfile38 as zipfile
```

**Comment by wasertech** [comment]
I've tested the fix. It works. PR is on the way.

**Comment by wasertech** [comment]
Since #2067 is now merged this issue is no more.
