### ISSUE TITLE
Error quick start on CentOS Linux release 7.9.2009 and python 3.6.8

### ISSUE THREAD

**Issue by alpody** [coqui-ai/STT#2069]
I use CentOS Linux release 7.9.2009 and python 3.6.8

```
$ python3 -V
Python 3.6.8

```
When i try quickstart command from https://stt.readthedocs.io/en/latest/
I got the error: 

```
Traceback (most recent call last):
  File "/home/webmaster/projects/python3/stt/venv-stt/bin/stt-model-manager", line 5, in <module>
    from coqui_stt_model_manager.__main__ import main
  File "/home/webmaster/projects/python3/stt/venv-stt/lib64/python3.6/site-packages/coqui_stt_model_manager/__main__.py", line 9, in <module>
    from .server import build_app, get_server_hostport, start_app
  File "/home/webmaster/projects/python3/stt/venv-stt/lib64/python3.6/site-packages/coqui_stt_model_manager/server.py", line 11, in <module>
    from queue import SimpleQueue
ImportError: cannot import name 'SimpleQueue'

```

```
$ pip list 

Package                 Version
----------------------- ---------
certifi                 2021.10.8
chardet                 4.0.0
click                   8.0.3
coqpit                  0.0.9
coqui-stt-model-manager 0.0.12
dataclasses             0.8
Flask                   2.0.1
Flask-Cors              3.0.10
Flask-SocketIO          4.3.2
idna                    2.10
importlib-metadata      4.8.3
itsdangerous            2.0.1
Jinja2                  3.0.1
MarkupSafe              2.0.1
numpy                   1.19.5
pip                     21.3.1
python-engineio         3.14.2
python-socketio         4.6.1
pyxdg                   0.27
requests                2.25.1
setuptools              39.2.0
six                     1.16.0
stt                     0.10.0a6
typing_extensions       4.0.1
urllib3                 1.26.8
webrtcvad               2.0.10
Werkzeug                2.0.2
zipp                    3.6.0

```

how fix it?

_Originally posted by @alpody in https://github.com/coqui-ai/STT/issues/2043#issuecomment-1009707683_

**Comment by reuben** [comment]
As mentioned on the other issue, we were missing an actual release push here. I just got it started: https://github.com/coqui-ai/stt-model-manager/actions/runs/1683518796

**Comment by reuben** [comment]
New version if up: https://pypi.org/project/coqui-stt-model-manager/0.0.19/

Can you retry the installation and test if it works now?

**Comment by alpody** [comment]
> New version if up: https://pypi.org/project/coqui-stt-model-manager/0.0.19/
> 
> Can you retry the installation and test if it works now?

I got same error:
Output hasn't changes 
```
 webmaster@localhost  ~/projects/python3/stt  rm  -rf ~/.cache/pip
 webmaster@localhost  ~/projects/python3/stt  python3 -m venv venv-stt
 webmaster@localhost  ~/projects/python3/stt  source venv-stt/bin/activate
(venv-stt)  webmaster@localhost  ~/projects/python3/stt  python3 -m pip install -U pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 818kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-21.3.1
(venv-stt)  webmaster@localhost  ~/projects/python3/stt  python3 -m pip install coqui-stt-model-manager
Collecting coqui-stt-model-manager
  Downloading coqui_stt_model_manager-0.0.19-py3-none-any.whl (599 kB)
     |████████████████████████████████| 599 kB 1.4 MB/s
Collecting webrtcvad==2.0.10
  Downloading webrtcvad-2.0.10.tar.gz (66 kB)
     |████████████████████████████████| 66 kB 3.1 MB/s
  Preparing metadata (setup.py) ... done
Collecting coqui-stt-model-manager
  Downloading coqui_stt_model_manager-0.0.12-py3-none-any.whl (620 kB)
     |████████████████████████████████| 620 kB 2.9 MB/s
Collecting stt==0.10.0a6
  Downloading stt-0.10.0a6-cp36-cp36m-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 6.4 MB/s
Collecting Flask-SocketIO==4.3.2
  Downloading Flask_SocketIO-4.3.2-py2.py3-none-any.whl (15 kB)
Collecting coqpit==0.0.9
  Downloading coqpit-0.0.9.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyxdg==0.27
  Downloading pyxdg-0.27-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 3.3 MB/s
Collecting Flask==2.0.1
  Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 1.8 MB/s
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.6 MB/s
Collecting Flask-Cors==3.0.10
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting Jinja2==3.0.1
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 1.4 MB/s
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting click>=7.1.2
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 2.7 MB/s
Collecting Werkzeug>=2.0
  Downloading Werkzeug-2.0.2-py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 3.7 MB/s
Collecting Six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting python-socketio<5,>=4.3.0
  Downloading python_socketio-4.6.1-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 556 kB/s
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 940 kB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 2.7 MB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 5.0 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 3.3 MB/s
Collecting numpy>=1.7.0
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 2.8 MB/s
Collecting importlib-metadata
  Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Collecting python-engineio<4,>=3.13.0
  Downloading python_engineio-3.14.2-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 1.4 MB/s
Collecting typing-extensions>=3.6.4
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Using legacy 'setup.py install' for webrtcvad, since package 'wheel' is not installed.
Building wheels for collected packages: coqpit
  Building wheel for coqpit (pyproject.toml) ... done
  Created wheel for coqpit: filename=coqpit-0.0.9-py3-none-any.whl size=12965 sha256=9d2cd0915eee309d05686a68968f728366ff1fc43ba9bde7a04f66cb8ec85261
  Stored in directory: /home/webmaster/.cache/pip/wheels/c7/47/45/2cffa13d1a7aab62cdfec76407999fc7bb2cb6950a9fd99606
Successfully built coqpit
Installing collected packages: zipp, typing-extensions, Six, MarkupSafe, importlib-metadata, dataclasses, Werkzeug, python-engineio, Jinja2, itsdangerous, click, urllib3, python-socketio, numpy, idna, Flask, chardet, certifi, webrtcvad,
stt, requests, pyxdg, Flask-SocketIO, Flask-Cors, coqpit, coqui-stt-model-manager
    Running setup.py install for webrtcvad ... done
Successfully installed Flask-2.0.1 Flask-Cors-3.0.10 Flask-SocketIO-4.3.2 Jinja2-3.0.1 MarkupSafe-2.0.1 Six-1.16.0 Werkzeug-2.0.2 certifi-2021.10.8 chardet-4.0.0 click-8.0.3 coqpit-0.0.9 coqui-stt-model-manager-0.0.12 dataclasses-0.8 idna-2.10 importlib-metadata-4.8.3 itsdangerous-2.0.1 numpy-1.19.5 python-engineio-3.14.2 python-socketio-4.6.1 pyxdg-0.27 requests-2.25.1 stt-0.10.0a6 typing-extensions-4.0.1 urllib3-1.26.8 webrtcvad-2.0.10 zipp-3.6.0
(venv-stt)  webmaster@localhost  ~/projects/python3/stt  pip list
Package                 Version
----------------------- ---------
certifi                 2021.10.8
chardet                 4.0.0
click                   8.0.3
coqpit                  0.0.9
coqui-stt-model-manager 0.0.12
dataclasses             0.8
Flask                   2.0.1
Flask-Cors              3.0.10
Flask-SocketIO          4.3.2
idna                    2.10
importlib-metadata      4.8.3
itsdangerous            2.0.1
Jinja2                  3.0.1
MarkupSafe              2.0.1
numpy                   1.19.5
pip                     21.3.1
python-engineio         3.14.2
python-socketio         4.6.1
pyxdg                   0.27
requests                2.25.1
setuptools              39.2.0
six                     1.16.0
stt                     0.10.0a6
typing_extensions       4.0.1
urllib3                 1.26.8
webrtcvad               2.0.10
Werkzeug                2.0.2
zipp                    3.6.0
(venv-stt)  webmaster@localhost  ~/projects/python3/stt  stt-model-manager
Traceback (most recent call last):
  File "/home/webmaster/projects/python3/stt/venv-stt/bin/stt-model-manager", line 5, in <module>
    from coqui_stt_model_manager.__main__ import main
  File "/home/webmaster/projects/python3/stt/venv-stt/lib64/python3.6/site-packages/coqui_stt_model_manager/__main__.py", line 9, in <module>
    from .server import build_app, get_server_hostport, start_app
  File "/home/webmaster/projects/python3/stt/venv-stt/lib64/python3.6/site-packages/coqui_stt_model_manager/server.py", line 11, in <module>
    from queue import SimpleQueue
ImportError: cannot import name 'SimpleQueue'
```
It begins download coqui_stt_model_manager-0.0.19-py3-none-any.whl 
But  pip list outputs:
coqui-stt-model-manager 0.0.12

**Comment by alpody** [comment]
> As mentioned on the other issue, we were missing an actual release push here. I just got it started: https://github.com/coqui-ai/stt-model-manager/actions/runs/1683518796
![firefox_lF1mLKxGbK](https://user-images.githubusercontent.com/13846803/149188647-d03ee770-05e0-4183-b5c0-327774fc7ae9.png)

In actions using python 3.9, but i have python 3.6.8

**Comment by reuben** [comment]
There's something really weird in your log. First it downloads coqui-stt-model-manager 0.0.19, and then it downloads it again, but version 0.0.12, and installs that version. As you can see in [the code](https://github.com/coqui-ai/stt-model-manager/blob/f5a19054f320768da2f7465b4cb1c1c9cb60ab0e/coqui_stt_model_manager/server.py#L11) that line does not exist in version 0.0.19. I don't understand why pip is behaving the way it is in your log, but if you manage to get the latest version installed it should work.

**Comment by alpody** [comment]
> There's something really weird in your log. First it downloads coqui-stt-model-manager 0.0.19, and then it downloads it again, but version 0.0.12, and installs that version. As you can see in [the code](https://github.com/coqui-ai/stt-model-manager/blob/f5a19054f320768da2f7465b4cb1c1c9cb60ab0e/coqui_stt_model_manager/server.py#L11) that line does not exist in version 0.0.19. I don't understand why pip is behaving the way it is in your log, but if you manage to get the latest version installed it should work.

When i try manual install:
pip install https://files.pythonhosted.org/packages/7a/5e/2ea6e01ca32f03e5099aa4b42e9d157f5d0d3e146550a593344929b07428/coqui_stt_model_manager-0.0.19-py3-none-any.whl

I got : 

```
Collecting coqui-stt-model-manager==0.0.19
  Using cached coqui_stt_model_manager-0.0.19-py3-none-any.whl (599 kB)
Requirement already satisfied: pyxdg==0.27 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (0.27)
Requirement already satisfied: requests==2.25.1 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (2.25.1)
Requirement already satisfied: Flask==2.0.1 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (2.0.1)
Requirement already satisfied: Flask-Cors==3.0.10 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (3.0.10)
Requirement already satisfied: Jinja2==3.0.1 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (3.0.1)
Requirement already satisfied: webrtcvad==2.0.10 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (2.0.10)
Requirement already satisfied: Flask-SocketIO==4.3.2 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (4.3.2)
Requirement already satisfied: coqpit==0.0.9 in ./venv-stt/lib/python3.6/site-packages (from coqui-stt-model-manager==0.0.19) (0.0.9)
ERROR: Could not find a version that satisfies the requirement stt==1.1.0 (from coqui-stt-model-manager) (from versions: 0.10.0a5, 0.10.0a6, 0.10.0a8, 0.10.0a9, 0.10.0a10)
ERROR: No matching distribution found for stt==1.1.0
```
When I try to install stt-1.1.0
```
pip install https://files.pythonhosted.org/packages/e2/c2/6b186482c0ee7134c5097cc46e4db49088dc0bb1201a142a946fc96dc49d/stt-1.1.0-cp36-cp36m-manylinux_2_24_x86_64.whl
ERROR: stt-1.1.0-cp36-cp36m-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.

```
I think coqui-stt-model-manager 0.0.19 required stt 1.1.0, but for my system can be install stt 0.10.0a6  only

**Comment by reuben** [comment]
Ah, then the problem is that we don't support your distro, we need glibc >= 2.24: https://stt.readthedocs.io/en/latest/SUPPORTED_PLATFORMS.html#linux-amd64

**Comment by alpody** [comment]
> Ah, then the problem is that we don't support your distro, we need glibc >= 2.24: https://stt.readthedocs.io/en/latest/SUPPORTED_PLATFORMS.html#linux-amd64

Centos 7 has glibc v2.17 and libstdc++ v4.8.5 
RockyLinux 8.5 has glibc v2.28 and libstdc++ v8.5.0

On RockyLinux 8.5 with python v3.9.6 all works.

Thank u
