### ISSUE TITLE
Bug: [webdataset on cloud storage] Error: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#2102]
**Describe the bug**

Training an STT model (in release docker container) with webdataset from *private* cloud storage (AWS S3) throws the following error:

`W tensorflow/core/framework/op_kernel.cc:1639] Invalid argument: TypeError: can't pickle _thread.lock objects`

data on S3 with public read access will work Ok, as will data hosted publicly, as in this github example.

```
$ docker run -it ghcr.io/coqui-ai/stt-train:v1.2.0
inside-docker# python -m coqui_stt_training.train --train_files 'https://github.com/coqui-ai/STT/blob/main/data/smoke_test/ldc93s1_wds.tar?raw=true' --test_files 'https://github.com/coqui-ai/STT/blob/main/data/smoke_test/ldc93s1_wds.tar?raw=true' -checkpoint_dir ./foo --alphabet_config_path data/alphabet.txt
```

However, we error out when the data is privately hosted on AWS S3, *even after awscli is configured*

Output:

```
root@josh:/code#  python -m coqui_stt_training.train --train_files https://private-s3-bucket/ldc93s1_wds.tar --checkpoint_dir ./foo --alphabet_config_path data/alphabet.txt --log_level 0
2022-02-09 00:39:28.711848: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
/usr/local/lib/python3.6/dist-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
2022-02-09 00:39:30.736328: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2245845000 Hz
2022-02-09 00:39:30.752700: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x518db80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-02-09 00:39:30.752767: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-02-09 00:39:30.755219: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2022-02-09 00:39:30.761884: E tensorflow/stream_executor/cuda/cuda_driver.cc:322] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-02-09 00:39:30.761908: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
I Performing dummy training to check for memory problems.
I If the following process crashes, you likely have batch sizes that are too big for your available system memory (or GPU memory).
WARNING:tensorflow:From /code/training/coqui_stt_training/train.py:341: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

D Session opened.
I Could not find best validating checkpoint.
I Could not find most recent checkpoint.
I Initializing all variables.
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                                            2022-02-09 00:39:43.162299: W tensorflow/core/framework/op_kernel.cc:1639] Invalid argument: TypeError: can't pickle _thread.lock objects
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 600, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/code/training/coqui_stt_training/util/feeding.py", line 179, in generate_values
    for sample_index, sample in enumerate(samples):

  File "/code/training/coqui_stt_training/util/augmentations.py", line 279, in apply_sample_augmentations
    yield from pool.imap(_load_and_augment_sample, timed_samples())

  File "/code/training/coqui_stt_training/util/helpers.py", line 155, in imap
    for obj in self.pool.imap(fun, self._limit(it)):

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)

  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))

  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)

TypeError: can't pickle _thread.lock objects


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: can't pickle _thread.lock objects
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 600, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/code/training/coqui_stt_training/util/feeding.py", line 179, in generate_values
    for sample_index, sample in enumerate(samples):

  File "/code/training/coqui_stt_training/util/augmentations.py", line 279, in apply_sample_augmentations
    yield from pool.imap(_load_and_augment_sample, timed_samples())

  File "/code/training/coqui_stt_training/util/helpers.py", line 155, in imap
    for obj in self.pool.imap(fun, self._limit(it)):

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)

  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))

  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)

TypeError: can't pickle _thread.lock objects


	 [[{{node PyFunc}}]]
	 [[tower_0/IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/training/coqui_stt_training/train.py", line 723, in <module>
    main()
  File "/code/training/coqui_stt_training/train.py", line 693, in main
    train()
  File "/code/training/coqui_stt_training/train.py", line 329, in train
    train_impl(epochs=1, reverse=True, limit=Config.train_batch_size * 3, write=False)
  File "/code/training/coqui_stt_training/train.py", line 566, in train_impl
    train_loss, _ = run_set("train", epoch, train_init_op)
  File "/code/training/coqui_stt_training/train.py", line 520, in run_set
    feed_dict={**feed_dict, **{epoch_ph: epoch}},
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: can't pickle _thread.lock objects
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 600, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/code/training/coqui_stt_training/util/feeding.py", line 179, in generate_values
    for sample_index, sample in enumerate(samples):

  File "/code/training/coqui_stt_training/util/augmentations.py", line 279, in apply_sample_augmentations
    yield from pool.imap(_load_and_augment_sample, timed_samples())

  File "/code/training/coqui_stt_training/util/helpers.py", line 155, in imap
    for obj in self.pool.imap(fun, self._limit(it)):

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value

  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)

  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))

  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)

TypeError: can't pickle _thread.lock objects


	 [[{{node PyFunc}}]]
	 [[tower_0/IteratorGetNext]]
```

**Comment by JRMeyer** [comment]
Got a working solution (thanks to @reuben for pointing in the right direction)

using the `pipe:command` logic you can stream a dataset from a private bucket as such:

`--train_files 'pipe:aws s3 cp s3://private-s3-bucket/my_webdataset.tar -'`

You first need to install `awscli` and then configure with `aws configure`, and then all should work:)
