### ISSUE TITLE
Bug: coqui_stt_training.transcribe

### ISSUE THREAD

**Issue by JRMeyer** [coqui-ai/STT#2160]
Hardware: MacBook (Retina, 12-inch, 2017)
OS: macOS Monterey 12.0.1

`coqui_stt_training.transcribe` errors out on macOS. From docker, I verified that this same command on Ubuntu runs as expected (i.e. throws webrtcvad dependency error), but on macOS throw this `RuntimeError: context has already been set`

```
$ docker run ghcr.io/coqui-ai/stt-train:main python -m coqui_stt_training.transcribe -h
                                                                                                                                                
================
== TensorFlow ==
================

NVIDIA Release 20.06-tf1 (build 13409399)
TensorFlow Version 1.15.2

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
Copyright 2017-2020 The TensorFlow Authors.  All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for TensorFlow.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...

WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/training/coqui_stt_training/transcribe.py", line 350, in <module>
    main()
  File "/code/training/coqui_stt_training/transcribe.py", line 335, in main
    multiprocessing.set_start_method("spawn")
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by reuben** [comment]
Can you clarify the connection between the issue description and the error log? Since the log is using the Docker image, that's an error happening on Linux, not macOS.
