### ISSUE TITLE
Bug: stt-model-manager crashes when following quickstart instructions

### ISSUE THREAD

**Issue by droundy** [coqui-ai/STT#2185]
**Describe the bug**

When I follow the [quickstart instructions](https://stt.readthedocs.io/en/latest/) I get a crash when I run `stt-model-manager`.

**To Reproduce**
1. `python3 -m venv venv-stt`
2. `source venv-stt/bin/activate`
3. `python -m pip install -U pip`
4. `python -m pip install coqui-stt-model-manager`
5. `stt-model-manager`

I then get
```
$ stt-model-manager
Traceback (most recent call last):
  File "/home/droundy/src/voice-control/venv-stt/bin/stt-model-manager", line 5, in <module>
    from coqui_stt_model_manager.__main__ import main
  File "/home/droundy/src/voice-control/venv-stt/lib/python3.9/site-packages/coqui_stt_model_manager/__main__.py", line 9, in <module>
    from .server import build_app, get_server_hostport, start_app
  File "/home/droundy/src/voice-control/venv-stt/lib/python3.9/site-packages/coqui_stt_model_manager/server.py", line 18, in <module>
    from flask_socketio import SocketIO
  File "/home/droundy/src/voice-control/venv-stt/lib/python3.9/site-packages/flask_socketio/__init__.py", line 24, in <module>
    from werkzeug.serving import run_with_reloader
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/home/droundy/src/voice-control/venv-stt/lib/python3.9/site-packages/werkzeug/serving.py)
```

**Expected behavior**
A browser tab will open and you can then download and test models from the Model Zoo.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian bullseye
- **Python version**: 3.9.2

**Comment by jizekki** [comment]
I had the same issue on MacOS. Downgrading werkzeug version to 2.0.3 solved the problem.

```bash
pip3 install werkzeug==2.0.3
```

**Comment by otozyon** [comment]
> I had the same issue on MacOS. Downgrading werkzeug version to 2.0.3 solved the problem.
> 
> ```shell
> pip3 install werkzeug==2.0.3
> ```

This fixed it for me as well (on macOS 11.6) but after that I get the following error when executing `stt-model-manager`:

`[1]    39541 illegal hardware instruction  stt-model-manager`

I'm running this on an M1 Macbook Air but I have the terminal emulating Intel architecture with Rosetta, so not quite sure if the M1 ARM architecture is the issue here.

**Comment by Lguyogiro** [comment]
same issue running Python 3.7 on Kubuntu. Downgrading werkzeug to 2.0.3 was the solution.
