### ISSUE TITLE
Model not working

### ISSUE THREAD

**Issue by tgwaste** [coqui-ai/STT#2209]
How do I make this work?

```
# /usr/local/bin/stt --model v1.0.0-huge-vocab --audio test.wav
Loading model from file v1.0.0-huge-vocab
TensorFlow: v2.8.0-8-g06c8fea58fd
 Coqui STT: v1.3.0-0-g148fa743
ERROR: Model provided has model identifier 'CTYP', should be 'TFL3'

Error at reading model file v1.0.0-huge-vocab
Traceback (most recent call last):
  File "/usr/local/bin/stt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/stt/client.py", line 148, in main
    ds = Model(args.model)
  File "/usr/local/lib/python3.10/dist-packages/stt/__init__.py", line 40, in __init__
    raise RuntimeError(
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)
```

**Comment by reuben** [comment]
`--model` should point to the acoustic model file, with `.tflite` extension. For the v1.0.0-huge-vocab model it can be downloaded from e.g. [here](https://coqui.ai/english/coqui/v1.0.0-huge-vocab)

**Comment by wasertech** [comment]
Closed as not an issue.
Please read https://stt.readthedocs.io/en/latest/DEPLOYMENT.html for more information about deployment and inference of a STT model.
