### ISSUE TITLE
Bug: FFMPEG: Missing dependency for some importers on STT 1.4.0

### ISSUE THREAD

**Issue by wasertech** [coqui-ai/STT#2212]
So I noticed a bug with the Att-HACK importer on STT 1.4.0 with python 3.8. This may be happening with other importer dependent on ffmpeg to convert samples such as ccpmf (checking now).

**Describe the bug**
Some importers can't convert samples.

**To Reproduce**
```bash
# Att-HACK
root@f00ea34c60fd:/code# ./bin/import_atthack.py --save_excluded_max_sec_to_disk /mnt/extracted/data/Att-HACK/Att-HACK_excluded_lm.txt  /mnt/extracted/data/Att-HACK/
WARNING: No --validate_label_locale specified, you might end with inconsistent dataset.
2022-05-13 14:44:00.671672: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Found archive "/mnt/extracted/data/Att-HACK/txt.tgz" - not downloading.
Found archive "/mnt/extracted/data/Att-HACK/wav.tgz" - not downloading.
No directory "/mnt/extracted/data/Att-HACK/Volumes/CLEM_HDD/IRCAM/Open_SLR/txt" - extracting archive...
No directory "/mnt/extracted/data/Att-HACK/Volumes/CLEM_HDD/IRCAM/Open_SLR/wav" - extracting archive...
Importing WAV files...
  0%|                                                                                                                    | 0/36634 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "./bin/import_atthack.py", line 143, in _maybe_convert_sets
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "./bin/import_atthack.py", line 92, in one_sample
    _maybe_convert_wav(original_wav, formatted_wav)
  File "./bin/import_atthack.py", line 299, in _maybe_convert_wav
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bin/import_atthack.py", line 372, in <module>
    _download_and_preprocess_data(target_dir=CLI_ARGS.target_dir)
  File "./bin/import_atthack.py", line 58, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_ROOT_PATH)
  File "./bin/import_atthack.py", line 174, in _maybe_convert_sets
    for i, processed in bar:
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

root@f00ea34c60fd:/code# ffmpeg --help
bash: ffmpeg: command not found
```

**Expected behavior**
This should work like on python 3.6 and extract the archives without issue.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  5.15.38-1-MANJARO (using docker)
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: (STT 1.4.0 -> TF 1.5.15-py38)
- **TensorFlow version (use command below)**: 1.5.15
- **Python version**: 3.8

**Additional context**
FFMPEG doesn't seems to be installed. Something to investigate futher.
All tests were done with #2213 for compatibility with 1.4.0

**Comment by wasertech** [comment]
So yes CCPMF is also affected.
```bash
root@acf5fbb62e72:/code# ./bin/import_ccpmf.py --save_excluded_max_sec_to_disk /mnt/extracted/data/ccpmf/ccpmf_excluded_lm.txt /mnt/extracted/data/ccpmf/                                                                                                                                            
WARNING: No --validate_label_locale specified, you might end with inconsistent dataset.
2022-05-13 15:33:37.974985: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.003" - downloading...
241172480it [04:00, 1001443.70it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.017" - downloading...
241172480it [04:02, 995416.42it/s] [[B
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.019" - downloading...
241172480it [02:53, 1386261.16it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.024" - downloading...
241172480it [02:16, 1772418.34it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.031" - downloading...
241172480it [01:08, 3508812.24it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.011" - downloading...
241172480it [01:10, 3439145.42it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.038" - downloading...
241172480it [01:15, 3177539.59it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.014" - downloading...
241172480it [02:05, 1919460.41it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.034" - downloading...
241172480it [02:07, 1889655.88it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.004" - downloading...
241172480it [02:03, 1957273.93it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.016" - downloading...
241172480it [04:44, 847262.04it/s] 
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.021" - downloading...
241172480it [03:24, 1177491.21it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.036" - downloading...
241172480it [04:30, 891412.52it/s] 
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.033" - downloading...
241172480it [01:11, 3389592.72it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.007" - downloading...
241172480it [01:13, 3260693.98it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.009" - downloading...
241172480it [01:14, 3230335.74it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.005" - downloading...
241172480it [01:12, 3323040.90it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.028" - downloading...
241172480it [01:14, 3251644.98it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.029" - downloading...
241172480it [01:14, 3229119.79it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.026" - downloading...
241172480it [01:14, 3226916.12it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.037" - downloading...
241172480it [01:14, 3247184.29it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.010" - downloading...
241172480it [01:11, 3391556.39it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.002" - downloading...
241172480it [01:14, 3233268.27it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.015" - downloading...
241172480it [01:48, 2223968.45it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.023" - downloading...
241172480it [01:41, 2376364.07it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.008" - downloading...
241172480it [02:38, 1524567.51it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.006" - downloading...
241172480it [01:14, 3218988.68it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.020" - downloading...
241172480it [01:12, 3305040.91it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.040" - downloading...
178833131it [00:53, 3326379.46it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.030" - downloading...
241172480it [03:11, 1260357.08it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.012" - downloading...
241172480it [01:12, 3329925.59it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.027" - downloading...
241172480it [01:10, 3428190.53it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.032" - downloading...
241172480it [01:09, 3452813.26it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.039" - downloading...
241172480it [01:18, 3070973.16it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.013" - downloading...
241172480it [01:12, 3336916.64it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.035" - downloading...
241172480it [01:13, 3264622.23it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.018" - downloading...
241172480it [01:14, 3255701.24it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.025" - downloading...
241172480it [01:09, 3479351.70it/s]
No archive "/mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.022" - downloading...
241172480it [01:12, 3338291.37it/s]
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.001 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.001: OK 863d39a06a388c6491c6ff2f6450b151f38f1b57
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.002 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.002: OK 2f3a0305aa04c61220bb00b5a4e553e45dbf12e1
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.003 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.003: OK 5e55e9f1f844097349188ac875947e5a3d7fe9f1
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.004 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.004: OK 8bf54842cf07948ca5915e27a8bd5fa5139c06ae
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.005 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.005: OK c8963504aadc015ac48f9af80058a0bb3440b94f
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.006 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.006: OK d95e225e908621d83ce4e9795fd108d9d310e244
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.007 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.007: OK de6ed9c2b0ee80ca879aae8ba7923cc93217d811
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.008 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.008: OK 234283c47dacfcd4450d836c52c25f3e807fc5f2
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.009 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.009: OK 4e6b67a688639bb72f8cd81782eaba604a8d32a6
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.010 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.010: OK 4165a51389777c8af8e6253d87bdacb877e8b3b0
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.011 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.011: OK 34322e7009780d97ef5bd02bf2f2c7a31f00baff
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.012 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.012: OK 48c5be3b2ca9d6108d525da6a03e91d93a95dbac
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.013 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.013: OK 87573172f506a189c2ebc633856fe11a2e9cd213
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.014 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.014: OK 6ab2c9e508e9278d5129f023e018725c4a7c69e8
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.015 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.015: OK 4f84df831ef46dce5d3ab3e21817687a2d8c12d0
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.016 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.016: OK e69bfb079885c299cb81080ef88b1b8b57158aa6
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.017 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.017: OK 5f764ba788ee273981cf211b242c29b49ca22c5e
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.018 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.018: OK b6aa81a959525363223494830c1e7307d4c4bae6
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.019 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.019: OK 91ddcf43c7bf113a6f2528b857c7ec22a50a148a
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.020 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.020: OK fa1b29273dd77b9a7494983a2f9ae52654b931d7
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.021 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.021: OK 1113aef4f5e2be2f7fbf2d54b6c710c1c0e7135f
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.022 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.022: OK ce6420d5d0b6b5135ba559f83e1a82d4d615c470
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.023 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.023: OK d0976ed292ac24fcf1590d1ea195077c74b05471
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.024 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.024: OK ec746cd6af066f62d9bf8d3b2f89174783ff4e3c
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.025 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.025: OK 570d9e1e84178e32fd867171d4b3aaecda1fd4fb
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.026 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.026: OK c29ccc7467a75b2cae3d7f2e9fbbb2ab276cb8ac
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.027 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.027: OK 08406a51146d88e208704ce058c060a1e44efa50
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.028 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.028: OK 199aedad733a78ea1e7d47def9c71c6fd5795e02
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.029 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.029: OK db856a068f92fb4f01f410bba42c7271de0f231a
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.030 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.030: OK e3c0135f16c6c9d25a09dcb4f99a685438a84740
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.031 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.031: OK e51b8bb9c0ae4339f98b4f21e6d29b825109f0ac
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.032 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.032: OK be5e80cbc49b59b31ae33c30576ef0e1a162d84e
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.033 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.033: OK 501df58e3ff55fcfd75b93dab57566dc536948b8
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.034 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.034: OK 1a114875811a8cdcb8d85a9f6dbee78be3e05131
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.035 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.035: OK 465d824e7ee46448369182c0c28646d155a2249b
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.036 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.036: OK 37f341b1b266d143eb73138c31cfff3201b9d619
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.037 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.037: OK 9e7d8255987a8a77a90e0d4b55c8fd38b9fb5694
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.038 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.038: OK 54886755630cb080a53098cb1b6c951c6714a143
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.039 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.039: OK 4b7cbb0154697be795034f7a49712e882a97197a
Checking transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.040 SHA1:
        transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip.040: OK c8e1e565a0e7a1f6ff1dbfcefe677aa74a41d2f2
No directory "/mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020" - extracting archive /mnt/extracted/data/ccpmf/transcriptionsxml_audiomp3_mefr_ccpmf_2012-2020_2.zip ...
here: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120524_transformations_urbaines_1_copie_wmv_2_fre_minefi.xml /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120524_transformations_urbaines_1_copie_wmv_0_fre_minefi.xml
here: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2014/20140327_france_chine_2_Gs_wmv_0_fre_minefi.xml /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2014/20140327_france_chine_2_Gs_wmv_2_fre_minefi.xml
here: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2014/20140327_France_Chine_1_wmv_0_fre_minefi.xml /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2014/20140327_France_Chine_1_wmv_2_fre_minefi.xml
here: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2015/20150122_Economie_Circulaire_wmv_0_fre_minefi.xml /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2015/20150122_Economie_Circulaire_2_wmv_0_fre_minefi.xml
here: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120524_transformations_urbaines_1_copie_wmv_2_fre_minefi.xml /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120524_transformations_urbaines_1_copie_wmv_0_fre_minefi.xml
Empty file /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120614_Defi_climat_2_copie_750_und.mp3 or /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120614_Defi_climat_2_copie_wmv_0_fre_minefi.xml
Missing XML pairs: ['/mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2016/20160614_Defi_Climat_2_750_und.mp3', '/mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2016/20160614_Defi_Climat_1_750_und.mp3', '/mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2014/20140411_Printemps_Economie_Copie_750_und.mp3']
Converting /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120525_forum_am_latine_caraibes_1_copie_750_fre.mp3 to WAV file: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/20120525_forum_am_latine_caraibes_1_copie_750_fre.wav
Source audio length: 1:40:54
Processing XML data: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120525_forum_am_latine_caraibes_1_copie_wmv_0_fre_minefi.xml
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "./bin/import_ccpmf.py", line 507, in one_sample
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bin/import_ccpmf.py", line 831, in <module>
    counter, rows = _maybe_import_data(
  File "./bin/import_ccpmf.py", line 636, in _maybe_import_data
    for i, processed in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by wasertech** [comment]
#2213 now installs `ffmpeg` with the other sound libs when building the docker image.
