### ISSUE TITLE
Bug: NotImplementedError: Cannot convert a symbolic Tensor (tower_0/cudnn_lstm/strided_slice_1:0) to a numpy array.

### ISSUE THREAD

**Issue by wasertech** [coqui-ai/STT#2219]
Before the training starts, the batch memory test fails with `NotImplementedError`.

```bash
+ python -m coqui_stt_training.train --show_progressbar true --train_cudnn true --alphabet_config_path /mnt/models/alphabet.txt --scorer_path /mnt/lm/kenlm.scorer --feature_cache /mnt/sources/feature_cache --train_files /mnt/extracted/data/Att-HACK/Att-HACK_train.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_train.csv,/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_train.csv,/mnt/extracted/data/trainingspeech/ts_2019-04-11_fr_FR_train.csv,/mnt/extracted/data/MLS/MLS_train.csv,/mnt/extracted/data/cv-fr/clips/train.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_train.csv --dev_files /mnt/extracted/data/Att-HACK/Att-HACK_dev.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_dev.csv,/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_dev.csv,/mnt/extracted/data/trainingspeech/ts_2019-04-11_fr_FR_dev.csv,/mnt/extracted/data/MLS/MLS_dev.csv,/mnt/extracted/data/cv-fr/clips/dev.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_dev.csv --test_files /mnt/extracted/data/Att-HACK/Att-HACK_test.csv,/mnt/extracted/data/African_Accented_French/African_Accented_French/African_Accented_French_test.csv,/mnt/extracted/data/M-AILABS/fr_FR/fr_FR_test.csv,/mnt/extracted/data/trainingspeech/ts_2019-04-11_fr_FR_test.csv,/mnt/extracted/data/MLS/MLS_test.csv,/mnt/extracted/data/cv-fr/clips/test.csv,/mnt/extracted/data/lingualibre/lingua_libre_Q21-fra-French_test.csv --train_batch_size 32 --dev_batch_size 16 --test_batch_size 16 --n_hidden 2048 --epochs 30 --learning_rate 0.0001 --dropout_rate 0.3 --lm_alpha 0.0 --lm_beta 0.0 --log_level=1 --early_stop true --checkpoint_dir /mnt/checkpoints/
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
I Performing dummy training to check for memory problems.
I If the following process crashes, you likely have batch sizes that are too big for your available system memory (or GPU memory).
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/trainer/stt/training/coqui_stt_training/train.py", line 727, in <module>
    main()
  File "/home/trainer/stt/training/coqui_stt_training/train.py", line 697, in main
    train()
  File "/home/trainer/stt/training/coqui_stt_training/train.py", line 333, in train
    train_impl(epochs=1, reverse=True, limit=Config.train_batch_size * 3, write=False)
  File "/home/trainer/stt/training/coqui_stt_training/train.py", line 393, in train_impl
    gradients, loss, non_finite_files = get_tower_results(
  File "/home/trainer/stt/training/coqui_stt_training/train.py", line 172, in get_tower_results
    avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(
  File "/home/trainer/stt/training/coqui_stt_training/train.py", line 90, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(
  File "/home/trainer/stt/training/coqui_stt_training/deepspeech_model.py", line 232, in create_model
    output, output_state = rnn_impl(layer_3, seq_length, previous_state, reuse)
  File "/home/trainer/stt/training/coqui_stt_training/deepspeech_model.py", line 134, in rnn_impl_cudnn_rnn
    output, output_state = rnn_impl_cudnn_rnn.cell(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in converted code:

    /usr/local/lib/python3.8/dist-packages/tensorflow_core/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:427 call
        initial_state = self._zero_state(batch_size)
    /usr/local/lib/python3.8/dist-packages/tensorflow_core/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:452 _zero_state
        res.append(array_ops.zeros(sp, dtype=self.dtype))
    /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/ops/array_ops.py:2338 zeros
        output = _constant_if_small(zero, shape, dtype, name)
    /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/ops/array_ops.py:2295 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:180 prod
        
    /home/trainer/stt-train/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3088 prod
        return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
    /home/trainer/stt-train/lib/python3.8/site-packages/numpy/core/fromnumeric.py:86 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:735 __array__
        raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"

    NotImplementedError: Cannot convert a symbolic Tensor (tower_0/cudnn_lstm/strided_slice_1:0) to a numpy array.
```

See my logs [here](https://gist.github.com/wasertech/955a4a29f4d8d843a03ab288d9c427df).
STT version: 1.4.0
TF from `nvcr.io/nvidia/tensorflow:22.02-tf1-py3` -> `1.15.5+nv22.2`

Note: I think we already know about this but couldn't find much on it, we need to document this behavior.

Pip's dependency resolver  might have a point here:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 1.15.5+nv22.2 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.22.3 which is incompatible.
dask-cudf 21.12.0a0+293.g0930f712e6 requires pandas<1.4.0dev0,>=1.0, but you have pandas 1.4.2 which is incompatible.
cudf 21.12.0a0+293.g0930f712e6 requires pandas<1.4.0dev0,>=1.0, but you have pandas 1.4.2 which is incompatible.
```

**Comment by wasertech** [comment]
If you stumble into the above error it's likey because dependencies for CorpraCreator have updated `numpy`. Just ensure you have a version within the required range: `numpy<1.19.0,>=1.16.0`.
If you also use CC, try to also meet the requirements for `cudf[pandas<1.4.0dev0,>=1.0]` and `dask-cudf[pandas<1.4.0dev0,>=1.0]` .
