### ISSUE TITLE
Bug: native_client/kenlm/build': No such file or directory when using Docker image 

### ISSUE THREAD

**Issue by SuperKogito** [coqui-ai/STT#2266]
**Describe the bug**
I am using the Docker image and trying to create `lm.binary` and `vocab-500000.txt` files using  `generate_lm.py` by following [the-playbook](https://stt.readthedocs.io/en/latest/playbook/SCORER.html#using-generate-lm-py-to-create-lm-binary-and-vocab-500000-txt-files), with the following command : 
```
root@4ceca53ccf56:/code# cd data/lm
root@4ceca53ccf56:/code/data/lm# python3 generate_lm.py  --input_txt /trainingdata/DeepSpeech/16khz-deepspeech-cleaner/languages/nl/text/nl_texts.txt \
--output_dir /trainingdata/DeepSpeech/16khz-deepspeech-cleaner/languages/nl/training/standard/nl_scorer \
--top_k 500000 --kenlm_bins /code/native_client/kenlm/build/bin/ \
--arpa_order 5 --max_arpa_memory "85%" --arpa_prune "0|0|1" \
--binary_a_bits 255 --binary_q_bits 8 --binary_type trie

Converting to lowercase and counting word occurrences ...
| |                      #                                                                                                                                                                              | 6997774 Elapsed Time: 0:02:00

Saving top 500000 words ...

Calculating word statistics ...
  Your text file has 126699875 words in total
  It has 2848796 unique words
  Your top-500000 words are 97.6596 percent of all words
  Your most common word "de" occurred 8421403 times
  The least common word in your top-k is "overledenen:" with 3 times
  The first word with 4 occurrences is "prijsbindingen" at place 494220

Creating ARPA file ...
Traceback (most recent call last):
  File "generate_lm.py", line 210, in <module>
    main()
  File "generate_lm.py", line 201, in main
    build_lm(args, data_lower, vocab_str)
  File "generate_lm.py", line 97, in build_lm
    subprocess.check_call(subargs)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/code/native_client/kenlm/build/bin/lmplz'
root@4ceca53ccf56:/code/data/lm# ls /code/native_client/kenlm/
.gitignore             CMakeLists.txt         COPYING.3              Doxyfile               LICENSE                README.coqui           clean_query_only.sh    compile_query_only.sh  setup.py               
BUILDING               COPYING                COPYING.LESSER.3       GIT_REVISION           MANIFEST.in            README.md              cmake/                 lm/                    util/                            
root@4ceca53ccf56:/code/data/lm# ls /code/native_client/kenlm/build
ls: cannot access '/code/native_client/kenlm/build': No such file or directory
root@4ceca53ccf56:/code/data/lm# 
```

**Expected behavior**
Generation of trie file.

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux cuda 4.15.0-171-generic #180-Ubuntu SMP Wed Mar 2 17:25:05 
- **CUDA/cuDNN version**: CUDA Version 10.0.130 / cuDNN 7.6.5
- **GPU model and memory**: GeForce RTX 2070 with 8 Gb 

So is this a Bug or am I missing something ? any help is appreciated. Thank you in advance.

**Comment by alpoktem** [comment]
Hi, I solved the KenLM problem by building it on my own together with its dependencies. Putting here as a temporal solution in case someone needs:
Inside the docker image:
```
apt-get update
sudo apt-get install build-essential libboost-all-dev cmake zlib1g-dev libbz2-dev liblzma-dev
cd /code
rm -r kenlm
git clone https://github.com/kpu/kenlm.git
mkdir -p build
cd build
cmake ..
make -j 4
```

**Comment by SuperKogito** [comment]
This worked for me. I simply had to build `kenlm` and move the build to the right path.
I am not sure if this is needed tho `sudo apt-get install build-essential libboost-all-dev cmake zlib1g-dev libbz2-dev liblzma-dev` but I could have already had installed those dependencies before. @alpoktem, thank you.

**Comment by HarikalarKutusu** [comment]
Yes, I've been using this one liner on Colab and point to that dir in STT calls:
```
# KenLM
!git clone https://github.com/kpu/kenlm.git && cd kenlm && mkdir build && cd build/ && cmake .. && make -j 4
```

**Comment by wasertech** [comment]
No no no that's not right if you use the docker image kenlm should come built with it.
Did you build the `Dockerfile.train` yourself? If so you need to make sure to initialize the kenlm submodule before running `docker build`.
```zsh
❯ git submodule update --init kenlm
❯ docker build --rm -f Dockerfile.train -t stt-train .
```

Trust me, it's easier to just pull the official image.
```
❯ docker pull ghcr.io/coqui-ai/stt-train:main
❯ docker run -it ghcr.io/coqui-ai/stt-train:main
# ls /code/kenlm/build/bin/
build_binary  fragment         lmplz                         query
count_ngrams  interpolate      phrase_table_vocab            streaming_example
filter        kenlm_benchmark  probing_hash_table_benchmark
```

**Comment by alpoktem** [comment]
@wasertech I had pulled and worked on the official docker image and kenlm wasn't working.

**Comment by wasertech** [comment]
@alpoktem I have an open fix for this.
[#2253](https://github.com/coqui-ai/STT/pull/2253/files#diff-48bc5269948447318d15029d2da42a23a56c64fa51ed147bf450d3f5623e38d6)
In the meantime, just install the missing libs manually.
```
# apt-get update
# apt-get install libboost-program-options-dev libboost-thread-dev
```
